/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.35
 * Generated at: 2016-07-01 04:51:23 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.chap8;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class siangsiu_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

final java.lang.String _jspx_method = request.getMethod();
if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
return;
}

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=utf-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("    \r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("    <title>Siang</title>\r\n");
      out.write("    <link href='https://fonts.googleapis.com/css?family=Indie+Flower' rel='stylesheet' type='text/css'>\r\n");
      out.write("    \r\n");
      out.write("    <!-- �λ��由곤옙�� -->\r\n");
      out.write("    <style>\r\n");
      out.write("    \t* { margin:0; padding:0;}\r\n");
      out.write("    \tbody { font-family: 'Times New Roman', serif; }\r\n");
      out.write("    \tli { list-style: none; }\r\n");
      out.write("    \ta { text-decoration: none; }\r\n");
      out.write("    \timg { border:0; }\r\n");
      out.write("    </style>\r\n");
      out.write("    \r\n");
      out.write("    <!-- 占쎈엘占쎈�� -->\r\n");
      out.write("    <style>\r\n");
      out.write("    \t#main_header {\r\n");
      out.write("    \t\r\n");
      out.write("    \t\twidth: 960px;\r\n");
      out.write("    \t\tmargin: 0 auto;\r\n");
      out.write("    \t\r\n");
      out.write("    \t\theight: 160px;\r\n");
      out.write("    \t\tposition: relative;\r\n");
      out.write("    \t}\r\n");
      out.write("    \t#main_header > #title{\r\n");
      out.write("    \t\tposition: absolute;\r\n");
      out.write("    \t\tleft: 20px; top: 30px;\r\n");
      out.write("    \t\t\r\n");
      out.write("    \t\t\r\n");
      out.write("    \t}\r\n");
      out.write("    \t#main_header > #main_gnb{\r\n");
      out.write("    \t\tposition: absolute;\r\n");
      out.write("    \t\tright: 0; top: 0;\r\n");
      out.write("    \t}\r\n");
      out.write("    \t#main_header > #main_lnb{\r\n");
      out.write("    \t\tposition: absolute;\r\n");
      out.write("    \t\tright: 0; bottom: 10px;\r\n");
      out.write("    \t}\r\n");
      out.write("    \t#login {\r\n");
      out.write("    \tposition: absolute;\r\n");
      out.write("    \t\tright: 0; bottom: 90px;\r\n");
      out.write("    \t}\r\n");
      out.write("    \r\n");
      out.write("    </style>\r\n");
      out.write("    \r\n");
      out.write("    <!-- 占쏙옙占쎌��占쏙옙 -->\r\n");
      out.write("    <style>\r\n");
      out.write("    \t#title {\r\n");
      out.write("    \t\tfont-family: 'Indie Flower', cursive;\r\n");
      out.write("    \t}\r\n");
      out.write("    </style>\r\n");
      out.write("    \r\n");
      out.write("    <!-- 筌�遺얜��(1) -->\r\n");
      out.write("    <style>\r\n");
      out.write("    \t#main_gnb > ul {overflow: hidden;}\r\n");
      out.write("    \t#main_gnb > ul > li { float: left;}\r\n");
      out.write("    \t#main_gnb > ul > li > a {\r\n");
      out.write("    \t\tdisplay: block;\r\n");
      out.write("    \t\tpadding: 2px 10px;\r\n");
      out.write("    \t\tborder:1px solid black;\r\n");
      out.write("    \t}\r\n");
      out.write("    \t#main_gnb > ul > li > a:hover {\r\n");
      out.write("    \t\tbackground:black;\r\n");
      out.write("    \t\tcolor: white;\r\n");
      out.write("    \t}\r\n");
      out.write("    \t#main_gnb > ul > li:first-child > a {border-radius:10px 0 0 10px;}\r\n");
      out.write("    \t#main_gnb > ul > li:last-child > a {border-radius:0 10px 10px 0;}\r\n");
      out.write("    \r\n");
      out.write("    </style>\r\n");
      out.write("    \r\n");
      out.write("    <!-- 筌�遺얜��(2) -->\r\n");
      out.write("    <style>\r\n");
      out.write("    \t#main_lnb > ul {overflow: hidden;}\r\n");
      out.write("    \t#main_lnb > ul > li { float: left;}\r\n");
      out.write("    \t#main_lnb > ul > li > a {\r\n");
      out.write("\t\t\tdisplay: block;\r\n");
      out.write("    \t\tpadding: 10px 20px;\r\n");
      out.write("    \t\tborder:1px solid black;\r\n");
      out.write("    \t}\r\n");
      out.write("    \t#main_lnb > ul > li > a:hover {\r\n");
      out.write("    \t\tbackground:black;\r\n");
      out.write("    \t\tcolor: white;\r\n");
      out.write("    \t}\r\n");
      out.write("    \t#main_lnb > ul > li:first-child > a {border-radius:10px 0 0 10px;}\r\n");
      out.write("    \t#main_lnb > ul > li:last-child > a {border-radius:0 10px 10px 0;}\r\n");
      out.write("    \r\n");
      out.write("    \t\r\n");
      out.write("    </style>\r\n");
      out.write("    \r\n");
      out.write("    <!-- ������筌ο옙 -->\r\n");
      out.write("    <style>\r\n");
      out.write("    \t#content {\r\n");
      out.write("    \t\twidth:960px;\r\n");
      out.write("    \t\tmargin: 0 auto;\r\n");
      out.write("    \t\t\r\n");
      out.write("    \t\toverflow:hidden;\r\n");
      out.write("    \t}\r\n");
      out.write("    \t\r\n");
      out.write("    \t#content > #main_section {\r\n");
      out.write("    \t\twidth:750px;\r\n");
      out.write("    \t\tfloat:left;\r\n");
      out.write("    \t}\r\n");
      out.write("    \t\r\n");
      out.write("    \t#content > #main_aside {\r\n");
      out.write("    \t\twidth:200px;\r\n");
      out.write("    \t\tfloat:right;\r\n");
      out.write("    \t}\r\n");
      out.write("    \t\r\n");
      out.write("    </style>\r\n");
      out.write("    \r\n");
      out.write("    <!-- 癰�紐�揆 -->\r\n");
      out.write("    <style>\r\n");
      out.write("    \t#main_section > article.main_article {\r\n");
      out.write("    \t\tmargin-bottom:10px;\r\n");
      out.write("    \t\tpadding:20px;\r\n");
      out.write("    \t\tborder:1px solid black;\r\n");
      out.write("    \t}\r\n");
      out.write("    </style>\r\n");
      out.write("    \r\n");
      out.write("    <!-- 占쎄�占쎌��占쎈굡 -->\r\n");
      out.write("    <style>\r\n");
      out.write("    \tinput:nth-of-type(1) { display:none;}\r\n");
      out.write("    \tinput:nth-of-type(1) ~ div:nth-of-type(1){ display: none;}\r\n");
      out.write("    \tinput:nth-of-type(1):checked ~ div:nth-of-type(1) { display:block;}\r\n");
      out.write("    \t\r\n");
      out.write("    \tinput:nth-of-type(2) { display:none;}\r\n");
      out.write("    \tinput:nth-of-type(2) ~ div:nth-of-type(2){ display: none;}\r\n");
      out.write("    \tinput:nth-of-type(2):checked ~ div:nth-of-type(2) { display:block;}\r\n");
      out.write("    \t\r\n");
      out.write("    \tsection.buttons { overflow: hidden;}\r\n");
      out.write("    \tsection.buttons > label {\r\n");
      out.write("    \t\tdisplay: block; float: left;\r\n");
      out.write("    \t\t\r\n");
      out.write("    \t\twidth: 100px; height: 30px;\r\n");
      out.write("    \t\tline-height:30px;\r\n");
      out.write("    \t\ttext-align:center;\r\n");
      out.write("    \t\t\r\n");
      out.write("    \t\tbox-sizing: border-box;\r\n");
      out.write("    \t\tborder: 1px solid black;\r\n");
      out.write("    \t\t\r\n");
      out.write("    \t\tbackground: black;\r\n");
      out.write("    \t\tcolor:white;\r\n");
      out.write("    \t\r\n");
      out.write("    \t}\r\n");
      out.write("    \tinput:nth-of-type(1):checked ~ section.buttons > label:nth-of-type(1) {\r\n");
      out.write("    \t\tbackground: white;\r\n");
      out.write("    \t\tcolor: black;\r\n");
      out.write("    \t}\r\n");
      out.write("    \tinput:nth-of-type(2):checked ~ section.buttons > label:nth-of-type(2) {\r\n");
      out.write("    \t\tbackground: white;\r\n");
      out.write("    \t\tcolor: black;\r\n");
      out.write("    \t}\r\n");
      out.write("    \r\n");
      out.write("    </style>\r\n");
      out.write("    \r\n");
      out.write("    <!-- 筌��몄� -->\r\n");
      out.write("    <style>\r\n");
      out.write("    \t.item {\r\n");
      out.write("    \t\toverflow: hidden;\r\n");
      out.write("    \t\tpadding: 10px;\r\n");
      out.write("    \t\tborder: 1px solid black;\r\n");
      out.write("    \t\tborder-top: none;\r\n");
      out.write("    \t}\r\n");
      out.write("    \t\r\n");
      out.write("    \t.thumbnail {\r\n");
      out.write("    \t\tfloat: left;\r\n");
      out.write("    \t}\r\n");
      out.write("    \t\r\n");
      out.write("    \t.description {\r\n");
      out.write("    \t\tfloat: left;\r\n");
      out.write("    \t\tmargin-left: 10px;\r\n");
      out.write("    \t}\r\n");
      out.write("    \t.description > strong {\r\n");
      out.write("    \t\tdisplay: block;\r\n");
      out.write("    \t\twidth:120px;\r\n");
      out.write("    \t\twhite-space: nowrap;\r\n");
      out.write("    \t\toverflow:hidden;\r\n");
      out.write("    \t\ttext-overflow:ellipsis;\r\n");
      out.write("    \t}\r\n");
      out.write("    \r\n");
      out.write("    </style>\r\n");
      out.write("    \r\n");
      out.write("    <!-- 占쎈�占쎄숲 -->\r\n");
      out.write("    <style>\r\n");
      out.write("    \t#main_footer {\r\n");
      out.write("    \twidth:960px; margin:0 auto;\r\n");
      out.write("    \tmargin-bottom:10px;\r\n");
      out.write("    \t\r\n");
      out.write("    \tbox-sizing: border-box;\r\n");
      out.write("    \tpadding:10px;\r\n");
      out.write("    \tborder:1px solid black;\r\n");
      out.write("    \t\r\n");
      out.write("    \ttext-align:center;\r\n");
      out.write("    </style>\r\n");
      out.write("    \r\n");
      out.write("</head>\r\n");
 request.setCharacterEncoding("euc-kr"); 
      out.write('\r');
      out.write('\n');

Object mem_name = session.getAttribute("member_name");
Object mem_id = session.getAttribute("member_id");
session.setAttribute("member_id", mem_id);


      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("    <header id=\"main_header\">\r\n");
      out.write("    \t<div id=\"title\">\r\n");
      out.write("    \t\t<h1>Rint Development</h1>\r\n");
      out.write("    \t\t<h2>HTML5 + CSS3 Basic</h2>\r\n");
      out.write("    \t</div>\r\n");
      out.write("    \t<nav id=\"main_gnb\">\r\n");
      out.write("    \t\t<ul>\r\n");
      out.write("    \t\t\t<li><a href=\"#\">Web</a></li>\r\n");
      out.write("    \t\t\t<li><a href=\"#\">Mobile</a></li>\r\n");
      out.write("    \t\t\t<li><a href=\"#\">Game</a></li>\r\n");
      out.write("    \t\t\t<li><a href=\"#\">Simulation</a></li>\r\n");
      out.write("    \t\t\t<li><a href=\"#\">Data</a></li>\r\n");
      out.write("    \t\t</ul>\r\n");
      out.write("    \t</nav>\r\n");
      out.write("    \t<nav id=\"login\">\r\n");
      out.write("    \t");
if(mem_name==null){    
      out.write("\r\n");
      out.write("    \t\t<a href=\"left_Frame.jsp\" >Login</a><br>\r\n");
      out.write("    \t\t");
} else { 
      out.write("\r\n");
      out.write("    \t\t<h3> user :  ");
      out.print(mem_name );
      out.write(" </h3>\r\n");
      out.write("    \t\t<a href=\"logout.jsp\">logout</a>\r\n");
      out.write("    \t\t");
} 
      out.write("\r\n");
      out.write("    \t</nav>\r\n");
      out.write("    \t<nav id=\"main_lnb\">\r\n");
      out.write("    \t\t<ul>\r\n");
      out.write("    \t\t\t<li><a href=\"#\">HTML5</a></li>\r\n");
      out.write("    \t\t\t<li><a href=\"#\">CSS3</a></li>\r\n");
      out.write("    \t\t\t<li><a href=\"#\">JavaScript</a></li>\r\n");
      out.write("    \t\t\t<li><a href=\"#\">jQuery</a></li>\r\n");
      out.write("    \t\t\t<li><a href=\"#\">Node.js</a></li>\r\n");
      out.write("    \t\t</ul>\r\n");
      out.write("    \t</nav>\r\n");
      out.write("    </header>\r\n");
      out.write("    \r\n");
      out.write("    <div id=\"content\">\r\n");
      out.write("    \t<section id=\"main_section\">\r\n");
      out.write("    \t\t<article class=\"main_article\">\r\n");
      out.write("    \t\t\t<h1>HelloFam</h1>\r\n");
      out.write("    \t\t\t<p>HelloDad HelloMom HelloPororri HelloSun HelloPato</p>\r\n");
      out.write("    \t\t</article>\r\n");
      out.write("    \t\t<article class=\"main_article\">\r\n");
      out.write("    \t\t\t<h1>HelloFam</h1>\r\n");
      out.write("    \t\t\t<p>HelloDad HelloMom HelloPororri HelloSun HelloPato</p>\r\n");
      out.write("    \t\t</article>\r\n");
      out.write("    \t\t<article class=\"main_article\">\r\n");
      out.write("    \t\t\t<h1>HelloFam</h1>\r\n");
      out.write("    \t\t\t<p>HelloDad HelloMom HelloPororri HelloSun HelloPato</p>\r\n");
      out.write("    \t\t</article>\r\n");
      out.write("    \t\t\r\n");
      out.write("    \t\r\n");
      out.write("    \t</section>\r\n");
      out.write("    \t<aside id=\"main_aside\">\r\n");
      out.write("    \t\t<input id=\"first\" type=\"radio\" name=\"tab\" checked=\"checked\" />\r\n");
      out.write("    \t\t<input id=\"second\" type=\"radio\" name=\"tab\"/>\r\n");
      out.write("    \t\t<section class=\"buttons\">\r\n");
      out.write("    \t\t\t<label for=\"first\">First</label>\r\n");
      out.write("    \t\t\t<label for=\"second\">Second</label>\r\n");
      out.write("    \t\t</section>\r\n");
      out.write("    \t\t<div class=\"tab_item\">\r\n");
      out.write("    \t\t\t<ul>\r\n");
      out.write("    \t\t\t\t<li class=\"item\">\r\n");
      out.write("\t    \t\t\t\t<a href=\"#\">\r\n");
      out.write("\t    \t\t\t\t\t<div class=\"thumbnail\">\r\n");
      out.write("\t    \t\t\t\t\t\t<img src=\"http://placehold.it/45x45\" />\r\n");
      out.write("\t    \t\t\t\t\t</div>\r\n");
      out.write("\t    \t\t\t\t\t<div class=\"description\">\r\n");
      out.write("\t    \t\t\t\t\t\t<strong>HTML5 Canvas</strong>\r\n");
      out.write("\t    \t\t\t\t\t\t<p>2012-03-15</p>\r\n");
      out.write("\t    \t\t\t\t\t</div>\r\n");
      out.write("\t    \t\t\t\t</a>\r\n");
      out.write("    \t\t\t\t</li>\r\n");
      out.write("    \t\t\t\t<li class=\"item\">\r\n");
      out.write("\t    \t\t\t\t<a href=\"#\">\r\n");
      out.write("\t    \t\t\t\t\t<div class=\"thumbnail\">\r\n");
      out.write("\t    \t\t\t\t\t\t<img src=\"http://placehold.it/45x45\" />\r\n");
      out.write("\t    \t\t\t\t\t</div>\r\n");
      out.write("\t    \t\t\t\t\t<div class=\"description\">\r\n");
      out.write("\t    \t\t\t\t\t\t<strong>HTML5 Audio</strong>\r\n");
      out.write("\t    \t\t\t\t\t\t<p>2012-03-15</p>\r\n");
      out.write("\t    \t\t\t\t\t</div>\r\n");
      out.write("\t    \t\t\t\t</a>\r\n");
      out.write("    \t\t\t\t</li>\r\n");
      out.write("    \t\t\t\t<li class=\"item\">\r\n");
      out.write("\t    \t\t\t\t<a href=\"#\">\r\n");
      out.write("\t    \t\t\t\t\t<div class=\"thumbnail\">\r\n");
      out.write("\t    \t\t\t\t\t\t<img src=\"http://placehold.it/45x45\" />\r\n");
      out.write("\t    \t\t\t\t\t</div>\r\n");
      out.write("\t    \t\t\t\t\t<div class=\"description\">\r\n");
      out.write("\t    \t\t\t\t\t\t<strong>HTML5 Video</strong>\r\n");
      out.write("\t    \t\t\t\t\t\t<p>2012-03-15</p>\r\n");
      out.write("\t    \t\t\t\t\t</div>\r\n");
      out.write("\t    \t\t\t\t</a>\r\n");
      out.write("    \t\t\t\t</li>\r\n");
      out.write("    \t\t\t\t<li class=\"item\">\r\n");
      out.write("\t    \t\t\t\t<a href=\"#\">\r\n");
      out.write("\t    \t\t\t\t\t<div class=\"thumbnail\">\r\n");
      out.write("\t    \t\t\t\t\t\t<img src=\"http://placehold.it/45x45\" />\r\n");
      out.write("\t    \t\t\t\t\t</div>\r\n");
      out.write("\t    \t\t\t\t\t<div class=\"description\">\r\n");
      out.write("\t    \t\t\t\t\t\t<strong>HTML Semantic Web</strong>\r\n");
      out.write("\t    \t\t\t\t\t\t<p>2012-03-15</p>\r\n");
      out.write("\t    \t\t\t\t\t</div>\r\n");
      out.write("\t    \t\t\t\t</a>\r\n");
      out.write("    \t\t\t\t</li>\r\n");
      out.write("    \t\t\t</ul>\r\n");
      out.write("    \t\t</div>\r\n");
      out.write("    \t\t<div class=\"tab_item\">\r\n");
      out.write("    \t\t\t<ul>\r\n");
      out.write("    \t\t\t\t<li class=\"item\">\r\n");
      out.write("\t    \t\t\t\t<a href=\"#\">\r\n");
      out.write("\t    \t\t\t\t\t<div class=\"thumbnail\">\r\n");
      out.write("\t    \t\t\t\t\t\t<img src=\"http://placehold.it/45x45\" />\r\n");
      out.write("\t    \t\t\t\t\t</div>\r\n");
      out.write("\t    \t\t\t\t\t<div class=\"description\">\r\n");
      out.write("\t    \t\t\t\t\t\t<strong>CSS3 Transition</strong>\r\n");
      out.write("\t    \t\t\t\t\t\t<p>2012-03-15</p>\r\n");
      out.write("\t    \t\t\t\t\t</div>\r\n");
      out.write("\t    \t\t\t\t</a>\r\n");
      out.write("    \t\t\t\t</li>\r\n");
      out.write("    \t\t\t\t<li class=\"item\">\r\n");
      out.write("\t    \t\t\t\t<a href=\"#\">\r\n");
      out.write("\t    \t\t\t\t\t<div class=\"thumbnail\">\r\n");
      out.write("\t    \t\t\t\t\t\t<img src=\"http://placehold.it/45x45\" />\r\n");
      out.write("\t    \t\t\t\t\t</div>\r\n");
      out.write("\t    \t\t\t\t\t<div class=\"description\">\r\n");
      out.write("\t    \t\t\t\t\t\t<strong>CSS3 Animation</strong>\r\n");
      out.write("\t    \t\t\t\t\t\t<p>2012-03-15</p>\r\n");
      out.write("\t    \t\t\t\t\t</div>\r\n");
      out.write("\t    \t\t\t\t</a>\r\n");
      out.write("    \t\t\t\t</li>\r\n");
      out.write("    \t\t\t\t<li class=\"item\">\r\n");
      out.write("\t    \t\t\t\t<a href=\"#\">\r\n");
      out.write("\t    \t\t\t\t\t<div class=\"thumbnail\">\r\n");
      out.write("\t    \t\t\t\t\t\t<img src=\"http://placehold.it/45x45\" />\r\n");
      out.write("\t    \t\t\t\t\t</div>\r\n");
      out.write("\t    \t\t\t\t\t<div class=\"description\">\r\n");
      out.write("\t    \t\t\t\t\t\t<strong>CSS3 Border</strong>\r\n");
      out.write("\t    \t\t\t\t\t\t<p>2012-03-15</p>\r\n");
      out.write("\t    \t\t\t\t\t</div>\r\n");
      out.write("\t    \t\t\t\t</a>\r\n");
      out.write("    \t\t\t\t</li>\r\n");
      out.write("    \t\t\t\t<li class=\"item\">\r\n");
      out.write("\t    \t\t\t\t<a href=\"#\">\r\n");
      out.write("\t    \t\t\t\t\t<div class=\"thumbnail\">\r\n");
      out.write("\t    \t\t\t\t\t\t<img src=\"http://placehold.it/45x45\" />\r\n");
      out.write("\t    \t\t\t\t\t</div>\r\n");
      out.write("\t    \t\t\t\t\t<div class=\"description\">\r\n");
      out.write("\t    \t\t\t\t\t\t<strong>CSS3 Box</strong>\r\n");
      out.write("\t    \t\t\t\t\t\t<p>2012-03-15</p>\r\n");
      out.write("\t    \t\t\t\t\t</div>\r\n");
      out.write("\t    \t\t\t\t</a>\r\n");
      out.write("    \t\t\t\t</li>\r\n");
      out.write("    \t\t\t</ul>\r\n");
      out.write("    \t\t\r\n");
      out.write("    \t\t</div>\r\n");
      out.write("    \t</aside>\r\n");
      out.write("    </div>\r\n");
      out.write("    <footer id=\"main_footer\">\r\n");
      out.write("    \t<h3>HTML5 + CSS3 Basic</h3>\r\n");
      out.write("    \t<address>Wdbsite Layout Basic</address>\r\n");
      out.write("    </footer>\r\n");
      out.write("    \r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
